name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.GH_TOKEN }}
          containerRegistry: true
      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://berserk.guide
          app: 'sveltekit'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/xmatic-squad/guide:latest'